name: Check and build

on: push

jobs:
  lint_build_deploy:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Build App
        run: yarn build

      - name: Deploy App
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages publish out --project-name jbethuel
